I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 427, in script
    noone "Tiens. Il s'appelle revient."
Exception: Sayer 'noone' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 427, in script
    noone "Tiens. Il s'appelle revient."
  File "/Applications/Renpy/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/Renpy/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'noone' is not defined.

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
RGUIG GAME 1.0
Sun Jun 19 16:11:18 2022
